### ISSUE TITLE
SocketAddress error (under Ventura)

### ISSUE THREAD

**Issue by jelemans** [vapor/mysql-nio#80] opened 2022-09-29 15:27 UTC
Just trying to start a project with mysql-nio.

The following calls;
 let socketAddress = try SocketAddress(ipAddress: "192.168.1.75", port: 3306)
 let connection = MySQLConnection.connect(to: try .makeAddressResolvingHost("192.168.1.75", port: 3306),...

both return an error dialog; The operation couldn’t be completed. (MySQLNIO.MySQLProtocol.HandshakeV10.Error error 0.)
and simultaneously crashing the debugger (Xcode 14).

top of the log;
 cmsMedical2                         0x0000000109e5435f $s8NIOPosix27MultiThreadedEventLoopGroupC014setupThreadAnddE033_C2B1528F4FBA68A3DBFA89DBAEBE9D4DLL4name06parentF015selectorFactory11initializerAA010SelectabledE0CSS_AcA8SelectorCyAA15NIORegistrationVGyKcyAA9NIOThreadCctFZ + 575
4   cmsMedical2                         0x0000000109e5512e $s8NIOPosix27MultiThreadedEventLoopGroupC18threadInitializers15selectorFactoryACSayyAA9NIOThreadCcG_AA8SelectorCyAA15NIORegistrationVGyKctcfcAA010SelectabledE0CyAGcXEfU_ + 734
5   cmsMedical2                         0x0000000109e580b0 $s8NIOPosix27MultiThreadedEventLoopGroupC18threadInitializers15selectorFactoryACSayyAA9NIOThreadCcG_AA8SelectorCyAA15NIORegistrationVGyKctcfcAA010SelectabledE0CyAGcXEfU_TA + 32
6   libswiftCore.dylib                  0x00007ff8199efe2e $sSlsE3mapySayqd__Gqd__7ElementQzKXEKlF + 462
7   cmsMedical2                         0x0000000109e54d7a $s8NIOPosix27MultiThreadedEventLoopGroupC18threadInitializers15selectorFactoryACSayyAA9NIOThreadCcG_AA8SelectorCyAA15NIORegistrationVGyKctcfc + 666
8   cmsMedical2                         0x0000000109e54ad4 $s8NIOPosix27MultiThreadedEventLoopGroupC18threadInitializers15selectorFactoryACSayyAA9NIOThreadCcG_AA8SelectorCyAA15NIORegistrationVGyKctcfC + 68
9   cmsMedical2                         0x0000000109e5495d $s8NIOPosix27MultiThreadedEventLoopGroupC15numberOfThreads15selectorFactoryACSi_AA8SelectorCyAA15NIORegistrationVGyKctcfC + 269
10  cmsMedical2                         0x0000000109e547bc $s8NIOPosix27MultiThreadedEventLoopGroupC15numberOfThreadsACSi_tcfC + 44
11  cmsMedical2                         0x0000000109b60e70 $s11cmsMedical28databaseCACycfc + 48
12  cmsMedical2                         0x0000000109b60e31 $s11cmsMedical28databaseCACycfC + 33
13  cmsMedical2                         0x0000000109b5ebf8 $s11cmsMedical24myDB_WZ + 24
14

**Comment by 0xTim** [comment] 2022-11-01 16:30
What version of MySQL are you connecting to and what security/password settings does it have set?

**Comment by gwynne** [comment] 2023-04-12 13:59
This is very likely a duplicate of #91 (i.e. the underlying issue is on the server side, MySQLNIO just doesn't show the error correctly yet).

**Comment by gwynne** [comment] 2023-05-09 02:15
Closing this out as a presumed duplicate of #91 due to lack of response from OP. Please feel free to reopen!

**Closed by gwynne** 2023-05-09 02:15 UTC
